version: "3.7"
services:
  scout-dev:
    image: "scout-new:development"
    container_name: scout-new-dev
    stdin_open: true
    build:
      target: development
    ports:
      - "3000"
    volumes:
      - ./:/app:cached
    environment:
      NODE_ENV: development
