version: "3.7"
services:
  scout:
    stdin_open: true
    image: "scout:production"
    container_name: scout-prod
    restart: unless-stopped
    build:
      target: production
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app:cached
    environment:
      NODE_ENV: production
    networks:
      - scout_dev_external_network
      - scout_dev_internal_network

networks:
  scout_dev_external_network:
  scout_dev_internal_network:
    internal: true
