[build]
    command = "npm run build"
    functions = "/functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
    package = "/plugins/netlify-add-netlify-build-vars"

[[plugins]]
    package = 'netlify-plugin-contextual-env'
        [plugins.inputs]
            mode = 'prefix'

