[build]
    base = "/"
    command = "echo branch"
    publish = "/"


[context.maintenance-mode]
    base = "/"
    command = "echo branch"
    publish = "/"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200